server:
  port: 8080

spring:
  application:
    name: cloud-payment-service
  redis:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait:  -1ms
        max-active: 8
      shutdown-timeout: 100ms
    host: 192.168.194.129
    password: test
    database: 0
    port: 6379